### PR TITLE
fix Method repr()

### PR DESCRIPTION
**Pull request by patiences**
While debugging I came across lines like: 
```
- Comparator: <bound method null.__eq__ of test>
``` 
Kept me on the wrong trail for a bit. Turns out `org.python.types.Type` objects on `org.python.types.Method`s don't have a `__name__` registered. This change uses `org.python.types.Type`'s `repr` method, resulting in logs like: 
```
- Comparator: <bound method <class 'str'>.__eq__ of test>
```

### CODE REVIEW

**Comment by eliasdorneles** [comment]
Any idea why compilation failed in the CI?

**Comment by patiences** [comment]
@eliasdorneles Ah, yes -- those failures have since been fixed in https://github.com/pybee/voc/pull/836. I'm not sure how to retrigger the build?

**Comment by eliasdorneles** [comment]
@patiences gotcha! So, if you synchronize the branch of this PR with master (either with merge or rebase), it will incorporate those changes and trigger a new build.
